name: Push to padsalatushal.githbub.io

on: push

jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Push to another repo
      uses: dmnemec/copy_file_to_another_repo_action@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }} 
      with:
        source_file: 'Edge_Removal.bat'
        destination_repo: 'padsalatushal/padsalatushal.github.io'
        user_email: 'padsalatushal@email.com' # your email
        user_name: 'padsalatushal'           # your login
        commit_message: 'update from source repo'
